import{S as p,i as c}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();async function y(t,r){const o=`https://pixabay.com/api/?key=43322409-71cdbf6ef8f62fb1f69ac5609&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`,e=await fetch(o);if(!e.ok)throw new Error("Network response was not ok");return e.json()}const f=new p("#gallery .image-card",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});async function m(t){const r=document.getElementById("gallery"),s=await Promise.all(t.map(async o=>await g(o)));r.append(...s),f.refresh()}async function g(t){const r=`
    <a class="image-card" href="${t.largeImageURL}">
      <img src="${t.webformatURL}" alt="${t.tags}">
      <div class="metadata-container">
        <p>Likes: ${t.likes}</p>
        <p>Views: ${t.views}</p>
        <p>Comments: ${t.comments}</p>
        <p>Downloads: ${t.downloads}</p>
      </div>
    </a>
  `,s=document.createElement("div");return s.innerHTML=r,s.firstElementChild}const d=document.querySelector(".load-btn"),u=document.querySelector("#search-input");let n=1,l=null;document.getElementById("search-form").addEventListener("submit",h);d.addEventListener("click",b);async function h(t){t.preventDefault(),n=1;const r=document.getElementById("gallery");r.innerHTML="";const s=document.getElementById("loader");s.style.display="block",l=u.value.trim();try{const o=await y(l);if(o.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");m(o.hits),o.total>15&&(d.style.display="block")}catch(o){c.error({title:"Error",message:o.message})}finally{s.style.display="none",u.value=""}}async function b(){n+=1;const t=document.getElementById("loader");t.style.display="block";try{const r=await y(l,n);m(r.hits);const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),Math.ceil(r.totalHits/15)===n&&(d.style.display="none",c.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",position:"bottomRight",backgroundColor:"#cb73fc",progressBar:!1,close:!1,timeout:5e3}))}catch(r){c.error({title:"Error",message:r.message})}finally{t.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
