import{a as g,S as h,i as d}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();async function u(e,t){const s="43322409-71cdbf6ef8f62fb1f69ac5609",n="https://pixabay.com/api/";try{return(await g.get(n,{params:{key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch{throw new Error("Network response was not ok")}}const w=new h("#gallery .image-card",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});async function y(e){const t=document.getElementById("gallery"),s=await Promise.all(e.map(async n=>await b(n)));t.append(...s),w.refresh()}async function b(e){const t=`
    <a class="image-card" href="${e.largeImageURL}">
      <img src="${e.webformatURL}" alt="${e.tags}">
      <div class="metadata-container">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `,s=document.createElement("div");return s.innerHTML=t,s.firstElementChild}const a=document.querySelector(".load-btn"),p=document.querySelector("#search-input"),E=document.getElementById("gallery"),l=document.getElementById("loader");let i=1,m="";document.getElementById("search-form").addEventListener("submit",L);a.addEventListener("click",v);a.style.display="none";async function L(e){e.preventDefault(),i=1,m=p.value.trim(),E.innerHTML="",l.style.display="block";try{const t=await u(m,i);if(t.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");y(t.hits),y(t.hits),t.total>15?a.style.display="block":a.style.display="none",f()}catch(t){d.error({title:"Error",message:t.message}),a.style.display="none"}finally{l.style.display="none",p.value=""}}async function v(){a.textContent="Loading...",i+=1,l.style.display="block";try{const e=await u(m,i);await y(e.hits),f(),Math.ceil(e.totalHits/15)===i&&(a.style.display="none",d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FDF5E6",position:"bottomRight",backgroundColor:"#FF4500",progressBar:!1,close:!1,timeout:5e3}))}catch(e){d.error({title:"Error",message:e.message})}finally{l.style.display="none",a.textContent="Load More"}}function f(){const e=document.querySelector("#gallery");if(e&&e.firstElementChild){const{height:t}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
